package model.entities;
// Generated 05-dic-2012 18:28:24 by Hibernate Tools 3.2.1.GA



/**
 * Mensajes generated by hbm2java
 */
public class Mensajes  implements java.io.Serializable {


     private long idMensaje;
     private Long idUsuario;
     private String mensaje;
     private String tema;

    public Mensajes() {
    }

	
    public Mensajes(long idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Mensajes(long idMensaje, Long idUsuario, String mensaje, String tema) {
       this.idMensaje = idMensaje;
       this.idUsuario = idUsuario;
       this.mensaje = mensaje;
       this.tema = tema;
    }
   
    public long getIdMensaje() {
        return this.idMensaje;
    }
    
    public void setIdMensaje(long idMensaje) {
        this.idMensaje = idMensaje;
    }
    public Long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(Long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getMensaje() {
        return this.mensaje;
    }
    
    public void setMensaje(String mensaje) {
        this.mensaje = mensaje;
    }
    public String getTema() {
        return this.tema;
    }
    
    public void setTema(String tema) {
        this.tema = tema;
    }




}


