package model.entities;
// Generated 05-dic-2012 18:28:24 by Hibernate Tools 3.2.1.GA



/**
 * Reenviados generated by hbm2java
 */
public class Reenviados  implements java.io.Serializable {


     private long idRe;
     private Long idUserEnvio;
     private Long idMensajeCitado;

    public Reenviados() {
    }

	
    public Reenviados(long idRe) {
        this.idRe = idRe;
    }
    public Reenviados(long idRe, Long idUserEnvio, Long idMensajeCitado) {
       this.idRe = idRe;
       this.idUserEnvio = idUserEnvio;
       this.idMensajeCitado = idMensajeCitado;
    }
   
    public long getIdRe() {
        return this.idRe;
    }
    
    public void setIdRe(long idRe) {
        this.idRe = idRe;
    }
    public Long getIdUserEnvio() {
        return this.idUserEnvio;
    }
    
    public void setIdUserEnvio(Long idUserEnvio) {
        this.idUserEnvio = idUserEnvio;
    }
    public Long getIdMensajeCitado() {
        return this.idMensajeCitado;
    }
    
    public void setIdMensajeCitado(Long idMensajeCitado) {
        this.idMensajeCitado = idMensajeCitado;
    }




}


