package model.entities;
// Generated 05-dic-2012 18:28:24 by Hibernate Tools 3.2.1.GA



/**
 * SeguirUsuarios generated by hbm2java
 */
public class SeguirUsuarios  implements java.io.Serializable {


     private long idSeg;
     private Long idUserOrigen;
     private Long idUserDestino;

    public SeguirUsuarios() {
    }

	
    public SeguirUsuarios(long idSeg) {
        this.idSeg = idSeg;
    }
    public SeguirUsuarios(long idSeg, Long idUserOrigen, Long idUserDestino) {
       this.idSeg = idSeg;
       this.idUserOrigen = idUserOrigen;
       this.idUserDestino = idUserDestino;
    }
   
    public long getIdSeg() {
        return this.idSeg;
    }
    
    public void setIdSeg(long idSeg) {
        this.idSeg = idSeg;
    }
    public Long getIdUserOrigen() {
        return this.idUserOrigen;
    }
    
    public void setIdUserOrigen(Long idUserOrigen) {
        this.idUserOrigen = idUserOrigen;
    }
    public Long getIdUserDestino() {
        return this.idUserDestino;
    }
    
    public void setIdUserDestino(Long idUserDestino) {
        this.idUserDestino = idUserDestino;
    }




}


