package model.entities;
// Generated 05-dic-2012 18:28:24 by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios  implements java.io.Serializable {


     private long idUsuario;
     private String usuario;
     private String email;
     private String password;

    public Usuarios() {
    }

	
    public Usuarios(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public Usuarios(long idUsuario, String usuario, String email, String password) {
       this.idUsuario = idUsuario;
       this.usuario = usuario;
       this.email = email;
       this.password = password;
    }
   
    public long getIdUsuario() {
        return this.idUsuario;
    }
    
    public void setIdUsuario(long idUsuario) {
        this.idUsuario = idUsuario;
    }
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


